### ISSUE TITLE
Integration with marshmallow

### ISSUE THREAD

**Issue by pedroivo000** [pedroivo000/notavel#1]
I need to integrate with the `marshmallow-mongoengine` library to convert the REST API requests objects to MongoDB objects and vice-versa. 

Currently there is a compatibility issue with `marshmallow-mongoengine` due to the `marshmallow._compact` module, that adds support for Python 2. As I would like to use this package, I need to install it from https://github.com/MongoEngine/marshmallow-mongoengine/pull/13.

**Comment by tschaume** [comment]
@pedroivo000 FYI I just merged MongoEngine/marshmallow-mongoengine#13 into master and will be working on getting a new version released on PyPI. It's probably best to not rely on the code in my fork anymore.

**Comment by pedroivo000** [comment]
@tschaume thanks for the heads up, but I decided to use a PostgreSQL database for my app, so I am not using MongoEngine/marshmallow-mongoengine anymore :)
